version: '3.1'

services: 
  app:
    working_dir: /var/www
    build:
      context: .
      dockerfile: ./Dockerfile
    # entrypoint: dockerize -wait tcp://db:3306 -timeout 40s sh ./.docker/entrypoint.sh
    entrypoint: dockerize sh ./.docker/entrypoint.sh
    tty: true
    # environment:
    #   - DB_HOST=db
    #   - DB_PORT=3306
    #   - DB_DATABASE=laravel
    #   - DB_USERNAME=root
    #   - DB_PASSWORD=root
    volumes: 
      - .:/var/www
    networks: 
      - app-network

  nginx:
    build: .docker/nginx
    restart: always
    tty: true
    ports:
      - "8001:80"
    volumes:
      - .:/var/www
    networks:
      - app-network
    depends_on: 
      - app

  # db:
  #   image: mysql:5.7
  #   command: --innodb-use-native-aio=0
  #   restart: always
  #   tty: true
  #   volumes:
  #     - .docker/mysql/dbdata:/var/lib/mysql
  #   env_file:
  #     - .docker/mysql/.env_mysql
  #   networks:
  #     - app-network

networks: 
  app-network:
    driver: bridge
